- name: Test switch connection
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Test CLI access
      cisco.ios.ios_command:
        commands:
          - show version
      register: result

    - debug:
        var: result.stdout_lines
